feature:
  - head-branch: ['^feature/', '^feat/']
bug:
  - head-branch: ['^bugfix/', '^bug/', '^fix/', '^hotfix/']
refactor:
  - head-branch: ['^refactor/']
dependencies:
  - head-branch: ['^dependabot/', '^keycloak/']
  - changed-files:
      - any-glob-to-any-file:
          - 'composer.json'
          - 'composer.lock'
          - 'e2e/package.json'
          - 'e2e/package-lock.json'
github_actions:
  - head-branch: ['^ci/']
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**/*'
          - '.github/*.yml'
documentation:
  - head-branch: ['^docs/', '^doc/']
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**/*'
          - '*.md'
          - 'LICENSE'
