name: joomla-external-login_devcontainer
services:

  keycloak:
    build: ./keycloak
    image: keycloak:cas
    restart: unless-stopped
    volumes:
      - type: volume
        source: keycloak_data
        target: /opt/keycloak/data
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-..}/.devcontainer/keycloak/export
        target: /opt/keycloak/data/export
        bind:
          create_host_path: true
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-..}/.devcontainer/keycloak/import
        target: /opt/keycloak/data/import
    command: start-dev --import-realm
    environment:
      # https://www.keycloak.org/server/configuration
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD:-admin}
      # https://www.keycloak.org/server/reverseproxy
      KC_PROXY_HEADERS: xforwarded
    ports:
      - 127.0.0.1:8080:8080
    networks:
      default:
        aliases:
          - auth.dev.local

  joomla:
    build:
      context: ./joomla
    image: joomla:external-login
    volumes:
      - type: volume
        source: joomla_data
        target: /var/www/html
      - type: volume
        source: joomla_log
        target: /var/www/html/administrator/logs
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-..}
        target: /workspace
        consistency: cached
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-..}/.devcontainer/php.ini
        target: /usr/local/etc/php/php.ini
        read_only: true
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-..}/.vscode
        target: /var/www/html/.vscode
        consistency: cached
    environment:
      JOOMLA_DB_HOST: ${JOOMLA_DB_HOST:-mysql}
      JOOMLA_DB_PASSWORD: ${JOOMLA_DB_PASSWORD:-${MYSQL_ROOT_PASSWORD:-secret}}
      # https://xdebug.org/docs/all_settings
      # XDEBUG_CONFIG: 'client_host=localhost log=/tmp/xdebug.log'
      # XDEBUG_MODE: develop,debug
    ports:
      - 127.0.0.1:80:80
    depends_on:
      - mysql
      - keycloak
    networks:
      default:
        aliases:
          - www.dev.local

  mysql:
    # https://hub.docker.com/_/mysql
    image: mysql
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-joomla}
    ports:
      - 127.0.0.1:3306:3306

volumes:
  joomla_data: null
  joomla_log: null
  keycloak_data: null
  mysql_data: null