version: '2'

services:
  joomla:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "8.1-apache-bullseye"
        JOOMLA_VERSION: "3.10.11"
    volumes:
      - ..:/workspace:cached
      - joomla-data:/var/www/html
    environment:
      JOOMLA_DB_HOST: mariadb
      JOOMLA_DB_PASSWORD: secret
    depends_on:
      - mariadb

  mariadb:
    # https://hub.docker.com/_/mariadb
    image: mariadb
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: joomla

volumes:
  joomla-data: null
  mariadb-data: null