version: '2'

services:
  keycloak:
    build: ./keycloak
    image: keycloak:cas
    restart: unless-stopped
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./keycloak/export:/opt/keycloak/data/export
      - ./keycloak/import:/opt/keycloak/data/import
    command: start --import-realm --optimized
    environment:
      # https://www.keycloak.org/server/configuration
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      # https://www.keycloak.org/server/all-config
      KC_HOSTNAME: auth.dev.local
      KC_HTTP_ENABLED: 'true'
      KC_PROXY: edge
    labels:
      - traefik.enable=true
      - traefik.http.routers.keycloak.entrypoints=websecure
      - traefik.http.routers.keycloak.rule=Host(`auth.dev.local`)
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
  
  joomla:
    build: .
    volumes:
      - ..:/workspace:cached
      - joomla-data:/var/www/html
    environment:
      JOOMLA_DB_HOST: mysql
      JOOMLA_DB_PASSWORD: secret
    external_links:
      - traefik:auth.dev.local
    labels:
      - traefik.enable=true
      - traefik.http.routers.joomla.entrypoints=websecure
      - traefik.http.routers.joomla.rule=Host(`www.dev.local`)
      - traefik.http.services.joomla.loadbalancer.server.port=8080
    depends_on:
      - mysql
      - keycloak

  mysql:
    # https://hub.docker.com/_/mysql
    image: mysql
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: joomla
    ports:
      - 127.0.0.1:3306:3306

  traefik:
    # https://hub.docker.com/_/traefik
    image: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./key.pem:/etc/traefik/key.pem:ro
      - ./cert.pem:/etc/traefik/cert.pem:ro
      - ./tls.yml:/etc/traefik/dynamic/tls.yml:ro
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.file.directory=/etc/traefik/dynamic/
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
      - 127.0.0.1:8080:8080

volumes:
  joomla-data: null
  keycloak-data: null
  mysql-data: null
