version: '2'

services:
  cas:
    # https://hub.docker.com/r/apereo/cas
    image: apereo/cas:6.6.9
    environment:
      # https://github.com/apereo/cas-overlay-template/blob/6.6/src/main/jib/docker/entrypoint.sh
      JVM_MEM_OPTS: -Xmx1g
      JVM_EXTRA_OPTS: -server -noverify
        -XX:+TieredCompilation -XX:TieredStopAtLevel=1
        -Dserver.ssl.enabled=false
        -Dserver.port=80
        -Dcas.authn.accept.users=user@example.org::secret

  joomla:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "8.1-apache-bookworm"
        JOOMLA_VERSION: "4.3.3"
    volumes:
      - ..:/workspace:cached
      - joomla-data:/var/www/html
    environment:
      JOOMLA_DB_HOST: mysql
      JOOMLA_DB_PASSWORD: secret
    depends_on:
      - mysql

  mysql:
    # https://hub.docker.com/_/mysql
    image: mysql
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: joomla

volumes:
  joomla-data: null
  mysql-data: null
