version: '2'

services:
  joomla:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "8.1-apache-bookworm"
        JOOMLA_VERSION: "4.3.3"
    volumes:
      - ..:/workspace:cached
      - joomla-data:/var/www/html
    environment:
      JOOMLA_DB_HOST: mysql
      JOOMLA_DB_PASSWORD: secret
    depends_on:
      - mysql

  mysql:
    # https://hub.docker.com/_/mysql
    image: mysql
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: joomla

volumes:
  joomla-data: null
  mysql-data: null